name: call_remote
on:
  workflow_call:
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch an action and get the run ID and URL
        uses: codex-/return-dispatch@v2
        id: return_dispatch
        with:
          token: ${{ secrets.TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: main # or refs/heads/target_branch
          repo: receive-action-poc
          owner: jordanjohnston
          workflow: main.yml
          workflow_inputs: '{}' # Optional
          workflow_timeout_seconds: 120 # Default: 300
          distinct_id: 'hi from call remote' # Optional
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.TOKEN }}
          repo: receive-action-poc
          owner: jordanjohnston
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 300 # Optional
          poll_interval_ms: 5000 # Optional
