name: call_remote
on:
  workflow_call:
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch an action and get the run ID and URL
        uses: codex-/return-dispatch@v2
        id: return_dispatch
        with:
          token: ${{ secrets.TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: main # or refs/heads/target_branch
          repo: receive-action-poc
          owner: jordanjohnston
          workflow: main.yml
          workflow_inputs: '{}' # Optional
          workflow_timeout_seconds: 120 # Default: 300
          distinct_id: 'hi from call remote' # Optional
      - name: Use the output run ID and URL
        run: |
          echo ${{steps.return_dispatch.outputs.run_id}}
          echo ${{steps.return_dispatch.outputs.run_url}}