name: main
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
#  test:
#    uses: ./.github/workflows/test.yml
  call_remote:
    uses: ./.github/workflows/call_remote.yml
#    needs: test
    secrets: inherit
  final:
    needs: call_remote
    uses: ./.github/workflows/final.yml
